q1 = Question.find_or_create_by!(text: "How active is your lifestyle?")
q2 = Question.find_or_create_by!(text: "Do you live in a house or an apartment?")
q3 = Question.find_or_create_by!(text: "How much time can you devote to a pet daily?")
q4 = Question.find_or_create_by!(text: "Do you have children or other pets?")
q5 = Question.find_or_create_by!(text: "Why do you want a pet?")
q6 = Question.find_or_create_by!(text: "How often do you travel?")
q7 = Question.find_or_create_by!(text: "What is your monthly budget for a pet?")
q8 = Question.find_or_create_by!(text: "How comfortable are you with grooming and cleanup?")
q9 = Question.find_or_create_by!(text: "What's your daily schedule like?")
q10 = Question.find_or_create_by!(text: "What kind of temperament are you looking for in a pet?")

a1_a = Answer.find_or_create_by!(question: q1, text: "Very active (hiking, running daily)")
a1_b = Answer.find_or_create_by!(question: q1, text: "Moderately active (walks, occasional activity)")
a1_c = Answer.find_or_create_by!(question: q1, text: "Not very active (sedentary, homebody)")
a2_a = Answer.find_or_create_by!(question: q2, text: "House with yard")
a2_b = Answer.find_or_create_by!(question: q2, text: "Apartment")
a2_c = Answer.find_or_create_by!(question: q2, text: "Small, shared space")
a3_a = Answer.find_or_create_by!(question: q3, text: "More than 3 hours/day")
a3_b = Answer.find_or_create_by!(question: q3, text: "1-3 hours/day")
a3_c = Answer.find_or_create_by!(question: q3, text: "Less than 1 hour/day")
a4_a = Answer.find_or_create_by!(question: q4, text: "Yes, children under 10")
a4_b = Answer.find_or_create_by!(question: q4, text: "Yes, I have a cat (not declawed)")
a4_c = Answer.find_or_create_by!(question: q4, text: "Yes, I have a declawed cat")
a4_d = Answer.find_or_create_by!(question: q4, text: "Yes, I have a friendly, social dog")
a4_e = Answer.find_or_create_by!(question: q4, text: "Yes, I have a dog and they prefer their space (senior dog, reactive dogs)")
Answer.find_or_create_by!(question: q4, text: "No")
a5_a = Answer.find_or_create_by!(question: q5, text: "Companionship/cuddle buddy")
a5_b = Answer.find_or_create_by!(question: q5, text: "Aesthetics/decoration")
a5_c = Answer.find_or_create_by!(question: q5, text: "Teach children responsibility")
Answer.find_or_create_by!(question: q6, text: "1-3 weeks/year")
a6_b = Answer.find_or_create_by!(question: q6, text: "4-6 weeks/year")
a6_c = Answer.find_or_create_by!(question: q6, text: "6+ weeks/year")
a7_a = Answer.find_or_create_by!(question: q7, text: "Less than $50")
a7_b = Answer.find_or_create_by!(question: q7, text: "$50-100")
a7_c = Answer.find_or_create_by!(question: q7, text: "$100+")
a8_a = Answer.find_or_create_by!(question: q8, text: "Fine with regular grooming/maintenance")
a8_b = Answer.find_or_create_by!(question: q8, text: "Prefer low maintenance pets")
a8_c = Answer.find_or_create_by!(question: q8, text: "Allergic/sensitive to odor")
Answer.find_or_create_by!(question: q9, text: "Home most of the day (remote work, retired)")
a9_b = Answer.find_or_create_by!(question: q9, text: "Gone during typical work hours (9-5)")
a9_c = Answer.find_or_create_by!(question: q9, text: "Irregular schedule (freelance)")
a10_a = Answer.find_or_create_by!(question: q10, text: "Laid-back, chill")
a10_b = Answer.find_or_create_by!(question: q10, text: "Playful and energetic")
a10_c = Answer.find_or_create_by!(question: q10, text: "Independent")
a10_d = Answer.find_or_create_by!(question: q10, text: "Affectionate and cuddly")

golden_retriever = RecommendedAnimal.find_or_create_by!(animal_type: "Golden Retriever", petf_type: "Dog", petf_breed: "Golden Retriever", photo_url: "https://images.unsplash.com/photo-1625679471452-647335d6cf68?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
corgi = RecommendedAnimal.find_or_create_by!(animal_type: "Corgi", petf_type: "Dog", petf_breed: "Corgi", photo_url: "https://plus.unsplash.com/premium_photo-1710406110954-fe2b58f118b0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
border_collie = RecommendedAnimal.find_or_create_by!(animal_type: "Border Collie", petf_type: "Dog", petf_breed: "Border Collie", photo_url: "https://plus.unsplash.com/premium_photo-1668862103939-3d2c1b0e4551?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
mastiff = RecommendedAnimal.find_or_create_by!(animal_type: "Mastiff", petf_type: "Dog", petf_breed: "Mastiff", photo_url: "https://images.unsplash.com/photo-1675025328975-037de094a7f1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
dachshund = RecommendedAnimal.find_or_create_by!(animal_type: "Dachshund", petf_type: "Dog", petf_breed: "Dachshund", photo_url: "https://images.unsplash.com/photo-1621757298919-50ce140ccb19?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
basset_hound = RecommendedAnimal.find_or_create_by!(animal_type: "Basset Hound", petf_type: "Dog", petf_breed: "Basset Hound", photo_url: "https://images.unsplash.com/photo-1619754226841-99b374dccbc0?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
cat = RecommendedAnimal.find_or_create_by!(animal_type: "Cat", petf_type: "Cat", petf_breed: nil, photo_url: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
small_mammal = RecommendedAnimal.find_or_create_by!(animal_type: "Small Mammal", petf_type: "Small & Furry", petf_breed: nil, photo_url: "https://plus.unsplash.com/premium_photo-1695410444708-ceb97017fac1?q=80&w=2067&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
bird = RecommendedAnimal.find_or_create_by!(animal_type: "Bird", petf_type: "Bird", petf_breed: nil, photo_url: "https://images.unsplash.com/photo-1736223526958-7035e069baba?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
amphibian_fish_reptile = RecommendedAnimal.find_or_create_by!(animal_type: "Amphibian Fish Reptile", petf_type: "Scales, Fins & Other", petf_breed: nil, photo_url: "https://images.unsplash.com/flagged/photo-1595577698735-520f16b5d90d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")
tamagotchi = RecommendedAnimal.find_or_create_by!(animal_type: "Tamagotchi", petf_type: "Robot", petf_breed: "Tamagotchi", photo_url: "https://images.unsplash.com/photo-1640519066824-9f76e650fc15?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")

a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.20)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.33)
a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.33)
a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.33)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.33)
a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.33)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.16)
a4_e.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a4_e.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)
a5_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a5_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.50)
a5_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 1.00)

a6_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a6_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.50)
a6_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a6_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)

a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.20)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a8_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a8_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)

a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.33)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)


user = User.find_or_create_by!(username: "drdoolittle")

animal = RecommendedAnimal.order("RANDOM()").first

submission = QuestionnaireSubmission.create!(
  user: user,
  recommended_animal: animal
)

answers = Question.all.map { |question| question.answers.sample }

answers.each do |answer|
  SubmissionAnswer.create!(
    questionnaire_submission: submission,
    answer: answer
  )
end

puts "Mock submission created for #{user.username} with #{answers.count} answers."

puts "I am seeded 🌱 PetFinders!"