q1 = Question.find_or_create_by!(text: "How active is your lifestyle?")
q2 = Question.find_or_create_by!(text: "Do you live in a house or an apartment?")
q3 = Question.find_or_create_by!(text: "How much time can you devote to a pet daily?")
q4 = Question.find_or_create_by!(text: "Do you have children or other pets?")
q5 = Question.find_or_create_by!(text: "Why do you want a pet?")
q6 = Question.find_or_create_by!(text: "How often do you travel?")
q7 = Question.find_or_create_by!(text: "What is your monthly budget for a pet?")
q8 = Question.find_or_create_by!(text: "How comfortable are you with grooming and cleanup?")
q9 = Question.find_or_create_by!(text: "What's your daily schedule like?")
q10 = Question.find_or_create_by!(text: "What kind of temperament are you looking for in a pet?")

a1_a = Answer.find_or_create_by!(question: q1, text: "Very active (hiking, running daily)")
a1_b = Answer.find_or_create_by!(question: q1, text: "Moderately active (walks, occasional activity)")
a1_c = Answer.find_or_create_by!(question: q1, text: "Not very active (sedentary, homebody)")
a2_a = Answer.find_or_create_by!(question: q2, text: "House with yard")
a2_b = Answer.find_or_create_by!(question: q2, text: "Apartment")
a2_c = Answer.find_or_create_by!(question: q2, text: "Small, shared space")
a3_a = Answer.find_or_create_by!(question: q3, text: "More than 3 hours/day")
a3_b = Answer.find_or_create_by!(question: q3, text: "1-3 hours/day")
a3_c = Answer.find_or_create_by!(question: q3, text: "Less than 1 hour/day")
a4_a = Answer.find_or_create_by!(question: q4, text: "Yes, children under 10")
a4_b = Answer.find_or_create_by!(question: q4, text: "Yes, I have a cat (not declawed)")
a4_c = Answer.find_or_create_by!(question: q4, text: "Yes, I have a declawed cat")
a4_d = Answer.find_or_create_by!(question: q4, text: "Yes, I have a friendly, social dog")
a4_e = Answer.find_or_create_by!(question: q4, text: "Yes, I have a dog and they prefer their space (senior dog, reactive dogs)")
Answer.find_or_create_by!(question: q4, text: "No")
a5_a = Answer.find_or_create_by!(question: q5, text: "Companionship/cuddle buddy")
a5_b = Answer.find_or_create_by!(question: q5, text: "Aesthetics/decoration")
a5_c = Answer.find_or_create_by!(question: q5, text: "Teach children responsibility")
Answer.find_or_create_by!(question: q6, text: "1-3 weeks/year")
a6_b = Answer.find_or_create_by!(question: q6, text: "4-6 weeks/year")
a6_c = Answer.find_or_create_by!(question: q6, text: "6+ weeks/year")
a7_a = Answer.find_or_create_by!(question: q7, text: "Less than $50")
a7_b = Answer.find_or_create_by!(question: q7, text: "$50-100")
a7_c = Answer.find_or_create_by!(question: q7, text: "$100+")
a8_a = Answer.find_or_create_by!(question: q8, text: "Fine with regular grooming/maintenance")
a8_b = Answer.find_or_create_by!(question: q8, text: "Prefer low maintenance pets")
a8_c = Answer.find_or_create_by!(question: q8, text: "Allergic/sensitive to odor")
Answer.find_or_create_by!(question: q9, text: "Home most of the day (remote work, retired)")
a9_b = Answer.find_or_create_by!(question: q9, text: "Gone during typical work hours (9-5)")
a9_c = Answer.find_or_create_by!(question: q9, text: "Irregular schedule (freelance)")
a10_a = Answer.find_or_create_by!(question: q10, text: "Laid-back, chill")
a10_b = Answer.find_or_create_by!(question: q10, text: "Playful and energetic")
a10_c = Answer.find_or_create_by!(question: q10, text: "Independent")
a10_d = Answer.find_or_create_by!(question: q10, text: "Affectionate and cuddly")

golden_retriever = RecommendedAnimal.find_or_create_by!(animal_type: "Golden Retriever", petf_type: "Dog", petf_breed: "Golden Retriever", photo_url: "https://images.unsplash.com/photo-1625679471452-647335d6cf68?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match result is Golden Retriever! These trusting, kind, and gentle dogs stand among America's most popular dog breeds. In weight, they average 50-75 pounds and have an average lifespan of 10-12 years. They are serious workers as they are a common choice for hunting, fieldwork, service dogs, and search and rescue. Goldens are friendly, intelligent, and eager-to-please family dogs. We've matched you with this energetic breed to fit your active lifestyle.")
corgi = RecommendedAnimal.find_or_create_by!(animal_type: "Corgi", petf_type: "Dog", petf_breed: "Corgi", photo_url: "https://plus.unsplash.com/premium_photo-1710406110954-fe2b58f118b0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match result is a Corgi! These strong, athletic, and lively little-legged herding dogs weigh on average 27-30 pounds and have a lifespan of 12-13 years. Although low to the ground, they are surprisingly quick and agile. These dogs are an intelligent and loving choice for a companion. Corgi's need for activity and bonding time with their human will match perfectly with your moderately active lifestyle and desire for a fiercely loyal, cuddly pet.")
border_collie = RecommendedAnimal.find_or_create_by!(animal_type: "Border Collie", petf_type: "Dog", petf_breed: "Border Collie", photo_url: "https://plus.unsplash.com/premium_photo-1668862103939-3d2c1b0e4551?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Border Collie! These remarkably intelligent dogs are great companions for owners with the time, energy, and means to keep them occupied. Border collies are constantly on the move, but these energetic dogs will settle down for cuddles when the workday is done. In weight, they average 30-55 pounds and have a lifespan of 12-15 years. With their athleticism and trainability, these dogs are best paired with humans like you, who can provide an outlet for their energy!")
mastiff = RecommendedAnimal.find_or_create_by!(animal_type: "Mastiff", petf_type: "Dog", petf_breed: "Mastiff", photo_url: "https://images.unsplash.com/photo-1675025328975-037de094a7f1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Mastiff! The colossal Mastiff is an ancient, dignified breed. On average these dogs have a lifespan of 6-10 years and can weigh 120-200 pounds! These dogs are extremely loyal, docile, and protective of family. Their size and tendency to be wary of strangers make early training and socialization essential. These dogs are happy to lounge or accompany you on your daily walk. Mastiffs are magnificent pets and they are quite literally a huge commitment, but with the right amount of space will be a joyful addition to your life!")
dachshund = RecommendedAnimal.find_or_create_by!(animal_type: "Dachshund", petf_type: "Dog", petf_breed: "Dachshund", photo_url: "https://images.unsplash.com/photo-1621757298919-50ce140ccb19?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Dachshund! These famously long, low-to-the-ground dogs make them an icon in the canine kingdom. On average, Dachshunds weigh 16-30 pounds (minis can be 11 pounds or less) and have a life expectancy of 12-16 years. While they are not built for distance running, leaping, or strenuous activity, Dachshunds are smart and playful and would love to accompany you on daily walks. The stubborn, brave, and endearing nature of this dog breed will win your heart over and make them a perfect match for your easy-going lifestyle." )
basset_hound = RecommendedAnimal.find_or_create_by!(animal_type: "Basset Hound", petf_type: "Dog", petf_breed: "Basset Hound", photo_url: "https://images.unsplash.com/photo-1619754226841-99b374dccbc0?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Basset Hound! This instantly recognizable hound is one of the most appealing breeds for dog lovers all over. On average, they weigh 40–65 pounds and have a life expectancy of 12–13 years. Bassets are famous for their extremely long, velvety ears and an uncanny scenting ability. This medium-sized breed is a great fit for families and individuals looking for an easy-going and loyal companion! They thrive in calm, loving homes and are known for their gentle temperament and humorous, sometimes stubborn personality. While they aren’t the most energetic dogs, they do enjoy leisurely walks and plenty of cozy nap spots." )
cat = RecommendedAnimal.find_or_create_by!(animal_type: "Cat", petf_type: "Cat", petf_breed: nil, photo_url: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: " Your best pet match is a Cat! Cats come in all shapes and sizes but their characteristics remain similar for all members of the feline family. The average domestic feline is anywhere from 8-15 pounds and lives 13-20 years. Cats are a great match for individuals looking for a cuddly, furry friend but may not have lots of time during the day to dedicate to their pet. In general, cats are independent and slow to adapt to big lifestyle changes (e.g. moving, getting another pet, or new members of the household), but once they're comfortable in their environment they provide endless entertainment and affection for their humans!")
small_mammal = RecommendedAnimal.find_or_create_by!(animal_type: "Small Mammal", petf_type: "Small & Furry", petf_breed: nil, photo_url: "https://plus.unsplash.com/premium_photo-1695410444708-ceb97017fac1?q=80&w=2067&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Small Mammal! This grouping of pets can include hamsters, gerbils, rats, mice, guinea pigs, ferrets, rabbits, and chinchillas. Rabbits, ferrets, and chinchillas on average live 5-10 years, rats and gerbils 2-3 years, and mice and hamsters 1.5-2 years. These small creatures make great pets because they’re low-maintenance, affectionate in their quirky ways, and easy to care for in smaller living spaces. Their playful behaviors and unique personalities can bring a lot of joy and companionship without requiring constant attention.")
bird = RecommendedAnimal.find_or_create_by!(animal_type: "Bird", petf_type: "Bird", petf_breed: nil, photo_url: "https://images.unsplash.com/photo-1736223526958-7035e069baba?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Parrot! This is a rare match on PetMatchMaker. Parrots are excellent, life-long companions and have extensive care requirements. Our questionnaire has evaluated your lifestyle and capability to care for these magnificent animals. Common birds that are kept as pets include parakeets, cockatiels, conures, doves, macaws, and African Grey parrots. Smaller parrots like cockatiels and parakeets have a lifespan of 15+ years. Larger parrots, like macaws and African Greys, can live 50+ years! These larger parrots have intelligence capabilities comparable to those of a 5-year-old human. If you take on the responsibility of a parrot you will be rewarded with an incredibly strong bond with one of the more fascinating creatures to exist on Earth.")
amphibian_fish_reptile = RecommendedAnimal.find_or_create_by!(animal_type: "Amphibian Fish Reptile", petf_type: "Scales, Fins & Other", petf_breed: nil, photo_url: "https://images.unsplash.com/flagged/photo-1595577698735-520f16b5d90d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is an Amphibian, Fish, or Reptile! Popular and easy-to-care-for options in this category include betta fish (lifespan: 3–5 years), leopard geckos (15–20 years), corn snakes (10–15 years), and African dwarf frogs (5–10 years). These pets are ideal for those who enjoy observing rather than constant handling, and they thrive in well-designed environments. While their enclosures do require attention to detail—like temperature control, appropriate substrate, and proper lighting—once their habitat is properly set up, daily care is not time-consuming. Small, scaly or slippery pets can be a fascinating, low-interaction way to bring nature indoors and create a peaceful, engaging presence in your home.")
tamagotchi = RecommendedAnimal.find_or_create_by!(animal_type: "Tamagotchi", petf_type: "Robot", petf_breed: "Tamagotchi", photo_url: "https://images.unsplash.com/photo-1640519066824-9f76e650fc15?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", description: "Your best pet match is a Tamagotchi! These classic digital pets are perfect for someone who wants the fun of pet ownership without the real-life mess, responsibility, or long-term commitment. Tamagotchis require minimal care—just regular virtual feedings and a little attention to keep them happy. They’re ideal for people with busy schedules, limited space, or anyone not quite ready for the real thing. Plus, if life gets hectic and your Tamagotchi “runs away,” you can always reset and try again. It’s all the joy of having a pet, with none of the fur, feeding schedules, or vet bills!" )

a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a1_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a1_b.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a1_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.20)
a2_a.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.20)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a2_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a2_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.33)
a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.33)
a3_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.33)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a3_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a3_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)

a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.33)
a4_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.33)
a4_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.33)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a4_c.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a4_d.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.16)
a4_e.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a4_e.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a5_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)
a5_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a5_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.50)
a5_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 1.00)

a6_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a6_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.50)
a6_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a6_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a7_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a7_b.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a7_c.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)

a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.20)
a8_a.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.20)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a8_b.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a8_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.50)
a8_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.50)

a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a9_b.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.33)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.25)
a9_c.recommended_animals_weights.find_or_create_by!(recommended_animal: bird, weight: 0.25)

a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: mastiff, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.25)
a10_a.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: border_collie, weight: 0.25)
a10_b.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.25)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: amphibian_fish_reptile, weight: 0.33)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: tamagotchi, weight: 0.33)
a10_c.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.33)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: dachshund, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: golden_retriever, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: cat, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: small_mammal, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: basset_hound, weight: 0.16)
a10_d.recommended_animals_weights.find_or_create_by!(recommended_animal: corgi, weight: 0.16)


user = User.find_or_create_by!(username: "drdoolittle")

animal = RecommendedAnimal.order("RANDOM()").first

submission = QuestionnaireSubmission.create!(
  user: user,
  recommended_animal: animal
)

answers = Question.all.map { |question| question.answers.sample }

answers.each do |answer|
  SubmissionAnswer.create!(
    questionnaire_submission: submission,
    answer: answer
  )
end

puts "Mock submission created for #{user.username} with #{answers.count} answers."

puts "I am seeded 🌱 PetFinders!"